package main

import (
	"database/sql"
	"os"
	"path/filepath"
	"testing"

	"profileunity-msp-console/internal/config"
	"profileunity-msp-console/internal/db"
)

// newValidDemoFile creates a fully-migrated (but otherwise empty) sqlite
// file at path, standing in for a real cmd/gendemodb-produced demo.db --
// schema-wise it's identical to one, which is all openDatabase's detection
// path inspects.
func newValidDemoFile(t *testing.T, path string) {
	t.Helper()
	sqlDB, err := db.Open("sqlite", path)
	if err != nil {
		t.Fatalf("create demo fixture: %v", err)
	}
	if err := sqlDB.Close(); err != nil {
		t.Fatalf("close demo fixture: %v", err)
	}
}

func baseConfig(t *testing.T, dsn string) config.Config {
	t.Helper()
	t.Setenv("PUMC_DB_DSN", dsn)
	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("config.Load: %v", err)
	}
	return cfg
}

func TestOpenDatabase_NoSidecarUsesRealDatabase(t *testing.T) {
	dir := t.TempDir()
	cfg := baseConfig(t, filepath.Join(dir, "profileunity-msp-console.db"))

	sqlDB, demoMode, err := openDatabase(cfg)
	if err != nil {
		t.Fatalf("openDatabase: %v", err)
	}
	defer sqlDB.Close()
	if demoMode {
		t.Error("demoMode = true, want false when no demo.db sidecar is present")
	}
}

func TestOpenDatabase_SidecarPresentUsesDemoDatabase(t *testing.T) {
	dir := t.TempDir()
	newValidDemoFile(t, filepath.Join(dir, db.DemoSidecarFilename))
	cfg := baseConfig(t, filepath.Join(dir, "profileunity-msp-console.db"))

	sqlDB, demoMode, err := openDatabase(cfg)
	if err != nil {
		t.Fatalf("openDatabase: %v", err)
	}
	defer sqlDB.Close()
	if !demoMode {
		t.Error("demoMode = false, want true when demo.db sidecar is present")
	}
}

func TestOpenDatabase_OverrideForcesRealDatabaseEvenWithSidecar(t *testing.T) {
	dir := t.TempDir()
	newValidDemoFile(t, filepath.Join(dir, db.DemoSidecarFilename))
	t.Setenv("PUMC_DEMO_MODE", "off")
	cfg := baseConfig(t, filepath.Join(dir, "profileunity-msp-console.db"))

	sqlDB, demoMode, err := openDatabase(cfg)
	if err != nil {
		t.Fatalf("openDatabase: %v", err)
	}
	defer sqlDB.Close()
	if demoMode {
		t.Error("demoMode = true, want false when PUMC_DEMO_MODE=off overrides a present sidecar")
	}
}

func TestOpenDatabase_CorruptSidecarFallsBackToRealDatabase(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, db.DemoSidecarFilename), []byte("not a sqlite file"), 0o600); err != nil {
		t.Fatalf("write corrupt fixture: %v", err)
	}
	cfg := baseConfig(t, filepath.Join(dir, "profileunity-msp-console.db"))

	sqlDB, demoMode, err := openDatabase(cfg)
	if err != nil {
		t.Fatalf("openDatabase: %v, want it to fall back to the real database instead of erroring", err)
	}
	defer sqlDB.Close()
	if demoMode {
		t.Error("demoMode = true, want false when the demo.db sidecar is corrupt")
	}
	if err := sqlDB.Ping(); err != nil {
		t.Errorf("the real database connection returned isn't usable: %v", err)
	}
}

func TestOpenDatabase_SchemaMismatchFallsBackToRealDatabase(t *testing.T) {
	dir := t.TempDir()
	demoPath := filepath.Join(dir, db.DemoSidecarFilename)
	newValidDemoFile(t, demoPath)

	// Simulate a demo.db generated by an older binary that's missing a
	// migration this one expects.
	sqlDB, err := sql.Open("sqlite", demoPath)
	if err != nil {
		t.Fatalf("reopen demo fixture: %v", err)
	}
	if _, err := sqlDB.Exec(`DELETE FROM schema_migrations WHERE filename = '0005_runtime_settings.sql'`); err != nil {
		t.Fatalf("simulate missing migration: %v", err)
	}
	if err := sqlDB.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	cfg := baseConfig(t, filepath.Join(dir, "profileunity-msp-console.db"))
	realDB, demoMode, err := openDatabase(cfg)
	if err != nil {
		t.Fatalf("openDatabase: %v, want it to fall back to the real database instead of erroring", err)
	}
	defer realDB.Close()
	if demoMode {
		t.Error("demoMode = true, want false when the demo.db sidecar has a schema mismatch")
	}
	if err := realDB.Ping(); err != nil {
		t.Errorf("the real database connection returned isn't usable: %v", err)
	}
}

func TestOpenDatabase_NonSqliteDriverIgnoresSidecar(t *testing.T) {
	dir := t.TempDir()
	newValidDemoFile(t, filepath.Join(dir, db.DemoSidecarFilename))
	t.Setenv("PUMC_DB_DRIVER", "postgres")
	cfg := baseConfig(t, filepath.Join(dir, "profileunity-msp-console.db"))

	_, demoMode, err := openDatabase(cfg)
	// postgres isn't implemented, so this is expected to error -- the
	// point of this test is only that it errors on the *postgres* path
	// (never implemented) rather than silently detecting the sidecar.
	if err == nil {
		t.Fatal("expected an error for the unimplemented postgres driver")
	}
	if demoMode {
		t.Error("demoMode = true, want false -- demo detection must not apply to a non-sqlite driver")
	}
}
