// Package web embeds the built frontend into the server binary.
//
// dist/ is produced by `ng build` in frontend/ (outputPath: "../dist" in
// angular.json), landing under dist/browser per Angular's application
// builder. It is git-ignored and regenerated by scripts/sync-version.sh's
// sibling frontend build step — see README.md "Building" — so `go build`
// run without building the frontend first fails loudly (no matching
// files for the go:embed pattern) rather than shipping a stale bundle.
package web

import "embed"

//go:embed dist
var Dist embed.FS

// DistDir is the subdirectory inside Dist that holds the site root, for
// use with http.FS via fs.Sub.
const DistDir = "dist/browser"
